{{- if .Values.worker_agents.cache_persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bb-cache
spec:
  {{- if .Values.worker_agents.cache_persistence.storageClassName }}
    {{- if (eq "-" .Values.worker_agents.cache_persistence.storageClassName) }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ .Values.worker_agents.cache_persistence.storageClassName }}"
    {{- end }}
  {{- end }}
  accessModes:
  {{- range .Values.worker_agents.cache_persistence.accessModes }}
     - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.worker_agents.cache_persistence.size | quote }}
{{- end }}
