{{- if .Values.serviceAccount.createRole -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: buildben-role-binding
subjects:
- kind: ServiceAccount
  name: buildben
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildben
{{- end }}
