apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-load-balancer
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  type: LoadBalancer
